file:
  # 分析文件根目录
  path: data
  name:
    stock:
      mm:
        file_name:
          in: a.csv
          out: mm
        # TODO
        target_year: 2022
        header:
          g: 4
          g_y2: 6
          g_y3: 5
          g_y10: 3

      fr:
        file_name: 
          in: a.csv
          out: boss
        # TODO
        target_year: 2023
        header:
          f:
            month:
              y: 12
              q1: 3
#              h: 6
#              q3: 9
            day:
              y: 31
              q1: 31
#              h: 30
#              q3: 30
          i: [30,40,45]
          j: 30
          k: 30

      money_flow:
        stock:
#          target_date: 2024-07-12
          file_name:
            in: a.csv
            out: a
          header:
            c: 30
            d: 10000
            o: 0.01

debug: true