file:
  # 分析文件根目录
  path: /data
  name:
    fund:
      ai:
        # run: true
        file_name:
          in:
            - a.csv
            - b.csv
          out: c
        cal_history_year: true
        header:
          e:
            - 0
            - 1
            - 3
            - 5
            - 8
            - 10
            - 30
            - 50
          COUNT: N
          RECOUNT: O
        headers:
          - F
          - G
          - H
          - I
          - J
          - K
          - L
          - M

    stock:
############ YEAR START ###############
      ai:
        # run: true
        file_name:
          in:
            - a.log
            - b.csv
          out: c
        # cal_history_year: true
        header:
          e:
            - 0
            - 1
            - 3
            - 5
            - 8
            - 10
            - 30
            - 50
            - -3
            - -6
          COUNT: P
          RECOUNT: Q
        headers:
          - F
          - G
          - H
          - I
          - J
          - K
          - L
          - M
          - N
          - O
############ YEAR END #################


############ MONTH START ###############
      mm:
        # run: true
        file_name:
          in: a.csv
          out: b
        # SB
        target_year: 2024
        header:
          g: 5
          g_y2: 6
          g_y5: 5
          g_y10: 3
      fr:
        # run: true
        file_name: 
          in: a.csv
          out: b
        # SB
        target_year: 2024
        header:
          f:
            month:
              # base data
              y: 12
#              q1: 3
              # h: 6
              q3: 9
            day:
              # base data
              y: 31
#              q1: 31
              # h: 30
              q3: 30
          i: [30,40,45]
          j: 30
          k: 30
############ MONTH END #################


############ DAILY START ###############
      ten_holder:
        run: true
        file_name:
          in: a.csv
          out: b
        ignores: []
        origins: [
                  ]
      money_flow:
        run: true
        stock:
          # target_date: 2025-10-29
#          o: true
          file_name:
            in: a.csv
            out: b
          header:
            c: 29
            d: 3000000
            o: 0.01
############ DAILY END #################

#debug: true