spring:
  application:
    name: octopus
#  data:
#    mongodb:
#      host: localhost
#      database: kitty

server:
  port: 19000
  servlet:
    context-path: /${spring.application.name}

logging:
  file:
    name: log/${spring.application.name}.log
    max-history: 2
    max-size: 1000MB
  level:
    #    org:
    #      apache:
    #        http: debug
    com:
      sun:
        caishenye: warn

################### 项目属性 ###############################
job:
  cron:
    # 2020-03-27 02:01:00 每天2点
    fund: 0 5 2 * * ?
    stock: 0 5 3 * * ?