#logging:
##  file:
##    name: log/${spring.application.name}.log
##    max-history: 2
##    max-size: 1000MB
#  level:
##    org:
##      apache:
##        http: info
#    com:
#      sun:
#        caishenye: info