spring:
  application:
    name: octopus

server:
  port: 9000
  servlet:
    context-path: /${spring.application.name}

logging:
  file:
    name: log/${spring.application.name}.log
  level:
    #    org:
    #      apache:
    #        http: debug
    com:
      sun:
        caishenye: debug
spring:
  data:
    mongodb:
      host: localhost
      database: kitty