spring:
  application:
    name: rubikcube
  data:
    mongodb:
      # 多个 IP 集群可以采用以下配置：
      # spring.data.mongodb.uri=mongodb://user:pwd@ip1:port1,ip2:port2/database
      uri: mongodb://root:root123@localhost:27017/caishenye
#  datasource:
#    druid:
#      driver-class-name:

server:
  port: 9001
  servlet:
    context-path: /${spring.application.name}

logging:
  file:
    name: log/${spring.application.name}.log
  level:
    #    org:
    #      apache:
    #        http: debug
    com:
      sun:
        caishenye: debug